version: "3.3"
services:
  db:
    image: "postgres:13"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=nestjs
    networks:
      - freecodecamp
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
networks:
  freecodecamp: